add/get/delete posts data using backend api
hendrik-kim/blog-mern pull request #29
Opened 2023-11-29 02:52 UTC by niniwoo

2023-12-01 08:31 UTC, hendrik-kim requested changes
Others shouldn't affect much else, but please check Persist for different versions.

2023-12-01 08:31 UTC, hendrik-kim commented on README.md
> +This will start both the frontend and backend services. Your frontend will be served at `http://localhost:3000` and your backend API can be accessed at `http://localhost:5001`.
We'll keep the port number on the backend server at 5000 and change it to 5001 if necessary.

2023-12-01 08:31 UTC, hendrik-kim commented on backend/controllers/postController.js
For the dummy data, please comment that it is for testing purposes only.

2023-12-01 08:31 UTC, hendrik-kim commented on backend/seeder.js
> +    // await createPosts(users);
Will change and test later when finalizing categories.

2023-12-01 08:31 UTC, hendrik-kim commented on frontend/package.json
> +  "proxy": "http://localhost:3000",
It's not really necessary, but it doesn't affect the system, so I think it's safe to leave it in.

2023-12-01 08:31 UTC, hendrik-kim commented on frontend/src/api/agent.js
> +// axios.defaults.withCredentials = true;
This is necessary for cookie security and should be restored. Please comment out if you need to.

2023-12-01 08:31 UTC, hendrik-kim commented on frontend/src/components/pages/AddPostForm.jsx
> +          timestamp: new Date().toLocaleTimeString(),
This is fine for input, but let's create a helper function to format it for later display on the frontend so that we can format it in a user-friendly way.

2023-12-01 08:31 UTC, hendrik-kim commented on frontend/src/components/pages/Home.jsx
> +          .filter((post) => post.postVisibility === "public")
For strings, consider defining them as immutable 'const' variable and using them like enums. 

const PUBLIC = "public";
....
.filter((post) => post.postVisibility === PUBLIC)

2023-12-01 08:31 UTC, hendrik-kim commented on frontend/src/components/pages/Mypage.jsx
> +            <p>posting time: {post.timestamp}</p>
Let's use a formatter helper for a more user-friendly way of displaying time, rather than just using the circular time.

2023-12-01 08:31 UTC, hendrik-kim commented on frontend/src/slices/postSlice.js
> +      const postEdit = await agent.Blog.updatePost();
Does the API call you're updating Post not have any argument data being input?

2023-12-01 08:31 UTC, hendrik-kim commented on package.json
>      "react-persist": "^1.0.2",
Do we use a different version of persist?

2023-12-04 21:32 UTC, sulgikim commented on .env.development
> +GOOGLE_CLIENT_SECRET="y"
Please avoid typo!

2023-12-04 21:32 UTC, sulgikim commented on backend/controllers/postController.js
> +  const { title, content, postVisibility, timestamp } = req.body;
Isn't category required?

2023-12-04 21:32 UTC, sulgikim commented on frontend/src/components/pages/AddPostForm.jsx
>    const [postVisibility, setPostVisibility] = useState("public");
I think we can use an object instead of having each states for better control and readability. 
ex) post = {
title: "", 
content: '", 
isVisible: true, 
}

2023-12-04 21:32 UTC, sulgikim commented on frontend/src/components/pages/AddPostForm.jsx
> +            <button type="button" onClick={onSavePostClicked}>
Instead of using onClick event, consider using onSubmit event in form tag. Using onSubmit is more semantically aligned with the purpose of a form, and it also provides better accessibility for users who may navigate the form using keyboard inputs.

2023-12-04 21:32 UTC, sulgikim commented on frontend/src/components/pages/Home.jsx
> +            <article key={i}>
Consider creating components for a single blog post and also a list of blog posts as they will be repeated in different pages.

2023-12-04 21:32 UTC, sulgikim commented on frontend/src/components/pages/Mypage.jsx
> +    dispatch(deletePost(postId));
I think this function should handle updates, not deletion.

2023-12-04 21:32 UTC, sulgikim commented on frontend/src/components/pages/Home.jsx
> +      {posts.posts && Array.isArray(posts.posts) && posts.posts.length > 0 ? (
Isn't posts.posts initialized as an empty array already? Why do you need to check isArray()?

2023-12-05 12:06 UTC, merged